export const CHANGE_INPUT_USER = 'LOGIN/CHANGE_INPUT_USER';
export const CHANGE_INPUT_PASS = 'LOGIN/CHANGE_INPUT_PASS';
export const LOGIN = 'LOGIN/LOGIN';
export const EXIT_LOGIN = 'LOGIN/EXIT_LOGIN';
